production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_devise: <%= ENV["SECRET_DEVISE"] %>
development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_devise: <%= ENV["SECRET_DEVISE"] %>
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_devise: <%= ENV["SECRET_DEVISE"] %>
